web:
    build: .
    links:
        - db
        - redis
    ports:
        - "9000:9000"

db:
    image: postgres:9.4
    environment:
        POSTGRES_PASSWORD: sentry
        POSTGRES_USER: sentry
    volumes:
        - postgres_data:/var/lib/postgresql/data

redis:
    image: redis
